"""deleted join tables

Revision ID: 0a5f0ee2667c
Revises: 2e6e36d7f5e5
Create Date: 2021-01-25 08:05:03.968823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5f0ee2667c'
down_revision = '2e6e36d7f5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grocery_users')
    op.drop_table('pantry_grocery_users')
    op.drop_table('freezer_grocery_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freezer_grocery_users',
    sa.Column('freezer_grocery_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['freezer_grocery_id'], ['freezer_groceries.id'], name='freezer_grocery_users_freezer_grocery_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='freezer_grocery_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('freezer_grocery_id', 'user_id', name='freezer_grocery_users_pkey')
    )
    op.create_table('pantry_grocery_users',
    sa.Column('pantry_grocery_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pantry_grocery_id'], ['pantry_groceries.id'], name='pantry_grocery_users_pantry_grocery_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pantry_grocery_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('pantry_grocery_id', 'user_id', name='pantry_grocery_users_pkey')
    )
    op.create_table('grocery_users',
    sa.Column('grocery_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['grocery_id'], ['groceries.id'], name='grocery_users_grocery_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='grocery_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('grocery_id', 'user_id', name='grocery_users_pkey')
    )
    # ### end Alembic commands ###
