"""added user_id to gorceries

Revision ID: 13aa94c57cd9
Revises: 90a7cb7d0e51
Create Date: 2021-01-07 03:07:24.543729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13aa94c57cd9'
down_revision = '90a7cb7d0e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groceries', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'groceries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groceries', type_='foreignkey')
    op.drop_column('groceries', 'user_id')
    # ### end Alembic commands ###
