"""added to types table

Revision ID: cdbfd59c2db8
Revises: d4857c4d166c
Create Date: 2021-01-06 07:25:53.150256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbfd59c2db8'
down_revision = 'd4857c4d166c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grocery_types', sa.Column('days_to_expiry', sa.Integer(), nullable=False))
    op.add_column('grocery_types', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grocery_types', 'image')
    op.drop_column('grocery_types', 'days_to_expiry')
    # ### end Alembic commands ###
